apiVersion: v2
name: cert-manager
description: Meta-chart for cert-manager
type: application
version: 1.0.24

dependencies:
  - name: cert-manager
    version: v1.19.4
    repository: https://charts.jetstack.io
