---
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: morganite
  namespace: wireguard
spec:
  type: ExternalName
  externalName: 192.168.10.58 # morganite
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard
  namespace: wireguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: wireguard.kyle2.net
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wireguard.kyle2.net
      secretName: wireguard-tls
  rules:
    - host: wireguard.kyle2.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: morganite
                port:
                  number: 8888
