apiVersion: v2
name: metallb
description: Meta-chart for MetalLB
type: application
version: 1.0.8

dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb
