apiVersion: v2
name: snapshot-controller
description: Meta-chart for snapshot-controller
type: application
version: 1.0.13

dependencies:
  - name: snapshot-controller
    version: 4.2.0
    repository: https://piraeus.io/helm-charts/
