apiVersion: v2
name: snapshot-controller
description: Meta-chart for snapshot-controller
type: application
version: 1.0.14

dependencies:
  - name: snapshot-controller
    version: 5.0.1
    repository: https://piraeus.io/helm-charts/
