apiVersion: v2
name: reloader
description: Meta-chart for reloader
type: application
version: 1.0.46

dependencies:
  - name: reloader
    version: 2.2.6
    repository: https://stakater.github.io/stakater-charts
