apiVersion: v2
name: reloader
description: Meta-chart for reloader
type: application
version: 1.0.45

dependencies:
  - name: reloader
    version: 2.2.5
    repository: https://stakater.github.io/stakater-charts
