apiVersion: v2
name: unifi
description: Meta-chart for UniFi
type: application
version: 2.0.104

dependencies:
  - name: mongodb
    version: 18.1.9
    repository: oci://registry-1.docker.io/bitnamicharts
