apiVersion: v2
name: unifi
description: Meta-chart for UniFi
type: application
version: 2.0.110

dependencies:
  - name: mongodb
    version: 18.3.0
    repository: oci://registry-1.docker.io/bitnamicharts
