---
# Container settings
# renovate: datasource=docker
wireguard_container_image: ghcr.io/wg-easy/wg-easy:15.1.0

# WireGuard settings
wireguard_host: vpn.kyle2.net
wireguard_dns: 192.168.10.58
wireguard_ipv4_cidr: 192.168.100.0/24
wireguard_disable_ipv6: true
wireguard_ui_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66313061306562356331306534306265656566323434653231333033616432306236626164653939
  6263323866373131323262303837626133656333313738620a623037356639373764623236346264
  62383161623139643262336435333132623135323666646461366431343761363562636639343161
  3263376435663364380a646563363439376264396634656131613566303731373431653365653538
  33636166613634343664333166336164656433396432643862323834396438346631343337386134
  6535643866336363623334303635666164396433363137393263
