---
# Container settings
# renovate: datasource=docker
wireguard_container_image: wgportal/wg-portal:v2.1.2

# core
wireguard_admin_user: admin@kyle2.net
wireguard_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66313061306562356331306534306265656566323434653231333033616432306236626164653939
  6263323866373131323262303837626133656333313738620a623037356639373764623236346264
  62383161623139643262336435333132623135323666646461366431343761363562636639343161
  3263376435663364380a646563363439376264396634656131613566303731373431653365653538
  33636166613634343664333166336164656433396432643862323834396438346631343337386134
  6535643866336363623334303635666164396433363137393263

# advanced
wireguard_start_cidr_v4: 192.168.100.0/24
wireguard_use_ip_v6: false

# database
wireguard_db_encryption_passphrase: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39343062626237646634633331643638333632393161306333653730326139643238366663383261
  3663623031343462373162386366306535646236323165360a353332653539663566343866353736
  36653861396664303839636264316665663163303232653135386431353838653166343834303739
  3632376638383136330a636135323331396363303937366330323063303065353736376439363635
  32333830646364643264653435326532666137383730386530383365623135643339383065663033
  66303666383162303565323830353166396332333664626238373339626232346464316337303665
  363065336436653864666239626464376633

# web
wireguard_web_listening_address: :51821
wireguard_web_external_url: https://wireguard.kyle2.net
wireguard_web_site_company_name: K2NET
wireguard_web_session_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65643236373735636535386162303165656538633536303661643966376430343233366636376162
  3763643131326237373738343730663630373036333564320a623234366237383534313135346138
  39626634613934366332626364663366323361663261373531313062346130363732643932326432
  3133306465376364320a663237333333396536356264343432386134323334386534386535623831
  62336163303465313465376534653666646661366363396431646663323466323238373436663066
  33386537626239353233366566313132383666303837396465663662626261303234613832653361
  343235653666323965363536623066666566
wireguard_web_csrf_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31323033346162646532666135313863366338386134363863633565386234633430623833616136
  3261613361326632666535323064623631643565386365370a323266663164646166613835366661
  36386430343335323266663433623731616332306666313438336561386234363132363264623661
  6331653330373262650a663061643730313238646364636261613539303037373063613661323434
  63643566383565333334393661323435633738343066363062336161643138363533383565346431
  63316334616137616632373739303366643138353363343761333939383234613765356233343632
  383935353438633331623033386332613230
