apiVersion: v2
name: grafana
description: Meta-chart for Grafana
type: application
version: 1.1.93

dependencies:
  - name: grafana
    version: 10.3.1
    repository: https://grafana.github.io/helm-charts
