apiVersion: v2
name: grafana
description: Meta-chart for Grafana
type: application
version: 1.1.91

dependencies:
  - name: grafana
    version: 10.2.0
    repository: https://grafana.github.io/helm-charts
