apiVersion: v2
name: grafana
description: Meta-chart for Grafana
type: application
version: 1.1.97

dependencies:
  - name: grafana
    version: 10.5.8
    repository: https://grafana.github.io/helm-charts
