apiVersion: v2
name: descheduler
description: Meta-chart for descheduler
type: application
version: 1.0.9

dependencies:
  - name: descheduler
    version: 0.35.0
    repository: https://kubernetes-sigs.github.io/descheduler
