apiVersion: v2
name: argocd
description: Meta-chart for 1Password Connect Operator
type: application
version: 1.0.12

dependencies:
  - name: connect
    version: 2.3.0
    repository: https://1password.github.io/connect-helm-charts
