apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.168

dependencies:
  - name: argo-cd
    version: 9.4.1
    repository: https://argoproj.github.io/argo-helm
