apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.163

dependencies:
  - name: argo-cd
    version: 9.2.4
    repository: https://argoproj.github.io/argo-helm
