apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.171

dependencies:
  - name: argo-cd
    version: 9.4.4
    repository: https://argoproj.github.io/argo-helm
