apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.159

dependencies:
  - name: argo-cd
    version: 9.1.7
    repository: https://argoproj.github.io/argo-helm
