apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.152

dependencies:
  - name: argo-cd
    version: 9.0.6
    repository: https://argoproj.github.io/argo-helm
