apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.1.161

dependencies:
  - name: argo-cd
    version: 9.1.9
    repository: https://argoproj.github.io/argo-helm
