---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/IAreKyleW00t/k2net
    targetRevision: main
    path: k8s/deploy/wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
