apiVersion: v2
name: ingress-nginx
description: Meta-chart for ingress-nginx
type: application
version: 1.0.19

dependencies:
  - name: ingress-nginx
    version: 4.14.3
    repository: https://kubernetes.github.io/ingress-nginx
